version: '2.2'

services:

  db-srv:
    image: postgres:11.1
    volumes:
      - pgdata:/var/lib/postgresql/data
      - '.dockerdev/init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  webpack-srv:
    build: .
    command:  bash -c "rm -rf /railsapp/public/packs; /railsapp/bin/webpack-dev-server"
    volumes:
      - '.:/railsapp'
      - bundle:/usr/local/bundle
      - node_modules:/railsapp/node_modules
    ports:
      - '3035:3035'
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  web-srv:
    build: .
    command: bash -c "rm -rf /railsapp/tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - '.:/railsapp'
      - bundle:/usr/local/bundle
      - node_modules:/railsapp/node_modules
    ports:
      - '127.0.0.1:3000:3000'
    depends_on:
      - db-srv
      - webpack-srv
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack-srv

volumes:
  bundle:
  pgdata:
  node_modules:
